services:
  - type: web
    name: mastra
    env: node
    plan: free
    buildCommand: |
      corepack enable
      corepack prepare pnpm@8.15.4 --activate
      pnpm install
    startCommand: pnpm run start
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: ANTHROPIC_API_KEY
        value: your-anthropic-api-key
