services:
  - type: web
    name: mastra-server
    env: node
    plan: free
    buildCommand: |
      corepack enable
      corepack prepare pnpm@latest --activate
      pnpm install
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        value: your-openai-key-here
      # Tambahin ENV lain kayak ANTHROPIC_API_KEY dll di sini
